const interface = require("./port");

const codes = {
    SAVE_GLOBALS: 0x10,
    SAVE_PROFILE: 0x11,
    TEMP_DEVICE: 0x12,
    SAVE_EXPLICIT: 0x13,
    SAVE_PROFILE_FLAGS: 0x14,
    FRAME_JUMP: 0x15,

    SEND_GLOBALS: 0x20,
    SEND_PROFILE: 0x21,

    READY_TO_RECEIVE: 0xA0,
    RECEIVE_SUCCESS: 0xA1,
    UART_READY: 0xA2,

    GLOBALS_UPDATED: 0xB0,

    CSGO_BEGIN: 0xC0,
    CSGO_NEW_STATE: 0xC1,
    CSGO_END: 0xCF,

    START_DEMO_MUSIC: 0xD0,
    START_DEMO_EFFECTS: 0xD1,
    END_DEMO: 0xDF,

    UNRECOGNIZED_COMMAND: 0xE0,
    BUFFER_OVERFLOW: 0xE1,

    DEBUG_PAUSE: 0xF0,
    DEBUG_RESUME: 0xF1,
    DEBUG_SET_FRAME: 0xF2,
    DEBUG_GET_FRAME: 0xF3,
    DEBUG_INCREMENT_FRAME: 0xF4
};

module.exports = interface;
module.exports.codes = codes;